<div id="lesson-chapter-create-modal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">创建章节</h4>
			</div>
			<div class="modal-body">
				<form method="post" class="form-horizontal" enctype="multipart/form-data">

					<div class="form-group">
						<div class="col-md-3 control-label"><label for="chaptername" class="required">章节名称</label></div>
						<div class="col-md-8 controls"><input type="text" name="chaptername" id="chaptername" required="required" class="form-control" /></div>
					</div>

					<div class="form-group">
						<div class="col-md-offset-3 col-md-8 controls">
							<a class="btn btn-fat btn-primary" href="#">创建</a>
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-offset-3 col-md-8 controls">
							<a target="_blank" class="text-muted" href="#">如何创建章节？</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>