<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><?= Phalcon\Tag::getTitle(FALSE) ?></title>
		<? $this->assets->outputCss() ?>
		<? $this->assets->outputJs() ?> 
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-static-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="/" class="navbar-brand">网络课堂</a>
				</div>
				<div class="navbar-collapse collapse">

					<ul class="nav navbar-nav navbar-right">
						<li><a href="#"><span class="glyphicon glyphicon-search"></span> 搜索</a></li>
						<li><a href="#"> 我的课程 </a></li>
						<li><a class="badge-container notification-badge-container" href="#">
								<span class="glyphicon glyphicon-bullhorn hidden-lt-ie8"></span>
								<span class="visible-lt-ie8">通知</span>
							</a></li>
						<li>
							<a class="badge-container message-badge-container" href="#">
								<span class="glyphicon glyphicon-envelope hidden-lt-ie8"></span>
								<span class="visible-lt-ie8">私信</span>
							</a>
						</li>
						<li class="visible-lt-ie8"><a href="#">管理员</a></li>
						<li class="dropdown hidden-lt-ie8">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">管理员 <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#"><i class="glyphicon glyphicon-home"></i> 我的主页</a></li>
								<li><a href="#"><i class="glyphicon glyphicon-cog"></i> 帐号设置</a></li>
								<li class="divider"></li>
								<li><a href="#"><i class="glyphicon glyphicon-dashboard"></i> 管理后台</a></li>
								<li class="divider"></li>
								<li><a href="#"><i class="glyphicon glyphicon-off"></i> 退出</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container-fluid">
			<?= $this->getContent() ?>
		</div>
	</body>
</html>
