<?php
${$this->view->getActionName()} = 'active';
var_dump();
?>
<div class="row-fluid">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="pull-right">
					<button class="btn btn-success btn-sm" data-toggle="modal" data-target="#course-create-modal">
						<span class="glyphicon glyphicon-ok-sign"></span> 
						发布
					</button>
					<button class="btn btn-success btn-sm" data-toggle="modal" data-target="#course-create-modal">
						<span class="glyphicon glyphicon-remove-circle"></span> 
						取消发布
				</button>
				</div>
				<img data-src="holder.js/50x50" class="img-thumbnail" />
				课程：如何进行有效的沟通
			</div>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				课程信息
			</div>
			<div class="list-group">
				<a class="list-group-item <?= ${'index'} ?>" href="/teach/course/index">基本信息</a>
				<a class="list-group-item <?= ${'lesson'} ?>" href="/teach/course/lesson">课时管理</a>
			</div>
			<div class="panel-heading">
				课程设置
			</div>
			<div class="list-group">
				<a class="list-group-item " href="#">价格设置</a>
				<a class="list-group-item " href="#">教师设置</a>
				<a class="list-group-item " href="#">学员管理</a>
			</div>
		</div>
	</div>
	<div class="col-md-9">

		<?= $this->getContent() ?>

	</div>
</div>
<script>
	$(function() {
		$('.chosen-select').chosen();
		$('.chosen-select-deselect').chosen({allow_single_deselect: true});
	});
</script>