<div class="row-fluid">	
	<div class="col-md-12">
		<div class="course-item-list-wrap">
			<ul class="course-item-list">
				<li class="item chapter-item clearfix">
					<span class="name">章节</span>
					<span class="title">进入客户的内心</span>
					<span class="pie">1</span>
				</li>
				<li class="item lesson-item lesson-item-finished clearfix">
					<span class="name">课时1</span>
					<a class="title" href="/edusoho/app.php/course/1/learn#lesson/1" title="通过聆听一首歌，发觉歌手当时所包含的感情。" data-id="1" data-experience="">
						通过聆听一首歌，发觉歌手当时所包含的感情。
						<span class="glyphicon  glyphicon-ok-circle" title="测验"></span>
					</a>
					<span class="type" title="音频时长03:26">
						<span>03:26</span>
						<span class="glyphicon glyphicon-volume-up"></span>
					</span>
					<span class="pie">&nbsp;</span>
					<a class="btn btn-default" href="/lesson">进入</a>
				</li>
				<li class="item lesson-item lesson-item-learning clearfix">
					<span class="name">课时2</span>
					<a class="title" href="/edusoho/app.php/course/1/learn#lesson/2" title="音乐创作与感情色彩之间的辩证探微" data-id="2" data-experience="">
						音乐创作与感情色彩之间的辩证探微
					</a>
					<span class="type">图文 <span class="glyphicon glyphicon-picture"></span></span>
					<span class="pie">&nbsp;</span>
				</li>
				<li class="item lesson-item clearfix">
					<span class="name">课时3</span>
					<a class="title" href="/edusoho/app.php/course/1/learn#lesson/2" title="音乐创作与感情色彩之间的辩证探微2" data-id="2" data-experience="">
						音乐创作与感情色彩之间的辩证探微2
					</a>
					<span class="type">图文 <span class="glyphicon glyphicon-picture"></span></span>
					<span class="pie">&nbsp;</span>
				</li>
				<li class="item chapter-item clearfix">
					<span class="name">章节</span>
					<span class="title">发觉客户的需求</span>
					<span class="pie">2</span>
				</li>
			</ul>
		</div>
	</div>
</div>
<script>
	$(function() {
		$('.course-item-list').sortable({items: ':not(.disabled)', placeholder: "item sortable-placeholder"});
	});
</script>