<div class="panel panel-default panel-col">
	<div class="panel-heading">基本信息</div>
	<div class="panel-body">
		<form class="form-horizontal" id="course-form" method="post">

			<div class="form-group">
				<div class="col-md-2 control-label"><label class="required">课程名</label></div>
				<div class="col-md-8 controls">
					<input type="text" name="coursename" required="required"    class="form-control" value="设计" />
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-2 control-label"><label class="required">摘要</label></div>
				<div class="col-md-8 controls">
					<textarea name="summary" required="required" class="form-control"></textarea>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-2 control-label"><label class="required">系统分类</label></div>
				<div class="col-md-8 controls">
					<select name="type_id" required="required" data-placeholder="请选择系统分类" class="form-control chosen-select" tabindex="2">
						<option value=""></option>
						<option value="1">销售</option>
					</select>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-2 control-label"><label class="required">自定义分类</label></div>
				<div class="col-md-8 controls">

					<select name="class_id" required="required" data-placeholder="请选择自定义分类" class="form-control chosen-select" tabindex="2">
						<option value=""></option>
						<option value="1">营销</option>
					</select>
				</div>
				<span class="help-block">管理自定义分类</span>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-8 controls">
					<input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>"/>
					<button class="btn btn-fat btn-primary" id="course-create-btn" type="submit">保存</button>
				</div>
			</div>

		</form>
	</div>
</div>
<script>
	$(function() {
		$('.chosen-select').chosen();
	});
</script>